[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 79
target-version = ['py38']

[tool.poetry]
name = "grand-challenge.org"
version = "0.1.0"
description = "A framework to objectively evaluate the performance of machine learning algorithms in biomedical imaging"
authors = ["James Meakin <code@jmsmkn.com>"]
packages = [
    { include = "app" },
]

[tool.poetry.dependencies]
python = "^3.8"
"beautifulsoup4" = "*"
celery = {extras = ["redis", "sqs"], version = "^4.4.6"}
django = "<3.2"
django-countries = "*"
django-crispy-forms = "*"
django-userena-ce = "*"
djangorestframework = "*"
docker = "*"
"oauth2" = "*"
python-magic = "*"
pytz = "*"
social-auth-app-django = "*"
gunicorn = "*"
uvicorn = "*"
django-celery-email = "*"
simpleitk = "*"
"psycopg2" = "*"
"django-select2" = "*"
django-celery-results = "*"
django-summernote = "*"
bleach = "*"
jsonschema = "*"
tldextract = "*"
tifffile = "==2019.1.4"
django-autocomplete-light = "*"
django-storages = "*"
boto3 = "*"
whitenoise = "*"
brotli = "*"
djangorestframework-guardian = "*"
django-extensions = "*"
django-simple-history = "*"
sentry-sdk = "*"
django-cors-headers = "*"
pyvips = "*"
pydicom = "*"
scikit-learn = "*"
pandas = "*"
xlrd = "*"
django-celery-beat = "!=1.6.0"
django-guardian = "!=2.2.0"
django-markdownx = "*"
django-filter = "*"
ua-parser = "*"
djangorestframework-csv = "*"
prometheus_client = "*"
openslide-python = "*"
humanize = "*"
disposable-email-domains = "*"
docutils = "<0.16" # Required for boto3 depedency resolution
django-machina = "*"
django-haystack = "3.0b1"
citeproc-py = "*"
django-ipware = "*"
pyswot = "*"
django-redis = "*"
drf-spectacular = "^0.13.0"

[tool.poetry.dev-dependencies]
pytest-django = "*"
pytest-cov = "*"
pytest-mock = "*"
factory-boy = "*"
django-debug-toolbar = "*"
sphinx-autobuild = "*"
sphinx = "*"
pyupgrade = "*"
pytest-xdist = "*"
sphinx-autodoc-typehints = "*"
werkzeug = "*"
sphinx-rtd-theme = "*"
sphinxcontrib-plantuml = "*"
pytest-randomly = "*"
